Controllers/MicrodataController.cs
using System.Web.Mvc;

namespace MicrodataMaker.Controllers
{
    public class MicrodataController : Controller
    {
        public ActionResult Person()
        {
            return View();
        }

        public ActionResult Event()
        {
            return View();
        }
        
        public ActionResult Organization()
        {
            return View();
        }

        public ActionResult Product()
        {
            return View();
        }

        public ActionResult Review()
        {
            return View();
        }

        public ActionResult Offer()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-1.7.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>Microdata</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink( "Person", "Person", "Microdata" )</li>
                    <li>@Html.ActionLink( "Event", "Event", "Microdata" )</li>
                    <li>@Html.ActionLink( "Organization", "Organization", "Microdata" )</li>
                    <li>@Html.ActionLink( "Product", "Product", "Microdata" )</li>
                    <li>@Html.ActionLink( "Review", "Review", "Microdata" )</li>
                    <li>@Html.ActionLink( "Offer", "Offer", "Microdata" )</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}